version: "3.8"
services:
 drupal:
  image: drupal:8-apache
  ports:
   - 8081:80
  volumes:
   - /var/www/html/modules
   - /var/www/html/profiles
   - /var/www/html/themes
   - /var/www/html/sites
  restart: always
 drupaldb:
  image: mysql
  command: --default-authentication-plugin=mysql_native_password
  restart: always
  volumes:
   - C:\Users\Francisco\DockerDespliegue\contenedores-compose:/var/lib/mysql
  environment:
   MYSQL_ROOT_PASSWORD: admin
   MYSQL_DATABASE: drupal